### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by avin** [dannycalleri/react-light-select#1]
Hello, Danny! Please add online demo for your project. Thank you ;)

**Comment by dannycalleri** [comment]
Hi @avin , thanks for posting the issue.
I'm working on the demo pages and close this one when I'm done.

**Comment by dannycalleri** [comment]
Here's the project page, including a simple demo:

[https://dannycalleri.github.io/react-light-select](dannycalleri.github.io/react-light-select)

Thanks again for posting the issue!
